updated the object store paths

diff --git a/docker-compose-ray.yaml b/docker-compose-ray.yaml
--- a/docker-compose-ray.yaml
+++ b/docker-compose-ray.yaml
@@ -1,43 +1,43 @@
 name: ray_cluster
 services:
   # MinIO object store service provides storage for artifacts, models
-  minio:
-    image: minio/minio
-    container_name: minio
-    restart: always
-    expose:
-      - "9000"
-    ports:  
-      - "9000:9000"  # The API for object storage is hosted on port 9000
-      - "9001:9001"  # The web-based UI is on port 9001
-    environment:
-      MINIO_ROOT_USER: "your-access-key"
-      MINIO_ROOT_PASSWORD: "your-secret-key"
-    healthcheck:
-      test: timeout 5s bash -c ':> /dev/tcp/127.0.0.1/9000' || exit 1
-      interval: 1s
-      timeout: 10s
-      retries: 5
-    command: server /data --console-address ":9001"
-    volumes:
-      - minio_data:/data  # Use a volume so minio storage persists beyond container lifetype
+  # minio:
+  #   image: minio/minio
+  #   container_name: minio
+  #   restart: always
+  #   expose:
+  #     - "9000"
+  #   ports:  
+  #     - "9000:9000"  # The API for object storage is hosted on port 9000
+  #     - "9001:9001"  # The web-based UI is on port 9001
+  #   environment:
+  #     MINIO_ROOT_USER: "your-access-key"
+  #     MINIO_ROOT_PASSWORD: "your-secret-key"
+  #   healthcheck:
+  #     test: timeout 5s bash -c ':> /dev/tcp/127.0.0.1/9000' || exit 1
+  #     interval: 1s
+  #     timeout: 10s
+  #     retries: 5
+  #   command: server /data --console-address ":9001"
+  #   volumes:
+  #     - minio_data:/data  # Use a volume so minio storage persists beyond container lifetype
 
   # When the minio service has started, launch a container with the minio client
   # and use it to create a bucket named mlflow-artifacts
-  minio-create-bucket:
-    image: minio/mc
-    depends_on:
-      minio:
-        condition: service_healthy
-    entrypoint: >
-      /bin/sh -c "
-      mc alias set minio http://minio:9000 your-access-key your-secret-key &&
-      if ! mc ls minio/mlflow-artifacts; then
-        mc mb minio/mlflow-artifacts &&
-        echo 'Bucket mlflow-artifacts creatd'
-      else
-        echo 'Bucket mlflow-artifacts already exists';
-      fi"
+  # minio-create-bucket:
+  #   image: minio/mc
+  #   depends_on:
+  #     minio:
+  #       condition: service_healthy
+  #   entrypoint: >
+  #     /bin/sh -c "
+  #     mc alias set minio http://minio:9000 your-access-key your-secret-key &&
+  #     if ! mc ls minio/mlflow-artifacts; then
+  #       mc mb minio/mlflow-artifacts &&
+  #       echo 'Bucket mlflow-artifacts creatd'
+  #     else
+  #       echo 'Bucket mlflow-artifacts already exists';
+  #     fi"
 
   # Postgresql server provides storage for parameters, metrics from experiment runs
   postgres:
@@ -57,21 +57,27 @@ services:
     image: ghcr.io/mlflow/mlflow:v2.20.2
     container_name: mlflow
     restart: always
-    depends_on:
-      - minio
+    depends_on:      
+      # - minio
       - postgres
-      - minio-create-bucket  # make sure minio and posgres services are alive, and bucket is created, before mlflow starts
+      # - minio-create-bucket  # make sure minio and posgres services are alive, and bucket is created, before mlflow starts
     environment:
       MLFLOW_TRACKING_URI: http://0.0.0.0:8000
-      MLFLOW_S3_ENDPOINT_URL: http://minio:9000  # how mlflow will access object store
-      AWS_ACCESS_KEY_ID: "your-access-key"
-      AWS_SECRET_ACCESS_KEY: "your-secret-key"
+      # MLFLOW_S3_ENDPOINT_URL: http://minio:9000  # how mlflow will access object store
+      # AWS_ACCESS_KEY_ID: "your-access-key"
+      # AWS_SECRET_ACCESS_KEY: "your-secret-key"
+    volumes:
+      - /mnt/object:/mnt/object:rw
     ports:
       - "8000:8000"
     command: >
-      /bin/sh -c "pip install psycopg2-binary boto3 &&
-      mlflow server --backend-store-uri postgresql://user:password@postgres/mlflowdb 
-      --artifacts-destination s3://mlflow-artifacts/ --serve-artifacts --host 0.0.0.0 --port 8000"
+      /bin/sh -c "pip install psycopg2-binary &&
+      mlflow server \
+        --backend-store-uri postgresql://user:password@postgres/mlflowdb \
+        --artifacts-destination /mnt/object/mlflow-artifacts \
+        --serve-artifacts \
+        --host 0.0.0.0 \
+        --port 8000"
       
   ray-head:
     image: rayproject/ray:2.42.1
@@ -91,14 +97,15 @@ services:
     shm_size: '12g'
     volumes:
       - ray_tmp:/tmp/ray
+      - /mnt/object:/mnt/object:rw
     environment:
       - RAY_GRAFANA_HOST=http://grafana:3000
       - RAY_GRAFANA_IFRAME_HOST=http://${HOST_IP}:3000
       - RAY_PROMETHEUS_HOST=http://ray-head:9090
       - RAY_PROMETHEUS_NAME=Prometheus
-      - AWS_ACCESS_KEY_ID=your-access-key     # for MinIO access
-      - AWS_SECRET_ACCESS_KEY=your-secret-key
-      - AWS_ENDPOINT_URL=http://minio:9000
+      # - AWS_ACCESS_KEY_ID=your-access-key     # for MinIO access
+      # - AWS_SECRET_ACCESS_KEY=your-secret-key
+      # - AWS_ENDPOINT_URL=http://minio:9000
     user: root
 
   grafana:
@@ -133,6 +140,8 @@ services:
     depends_on:
       - ray-head
 
+  
+
   ray-worker-1:
     build:
       context: .  # directory where Dockerfile.jupyter-ray is located
@@ -164,8 +173,13 @@ services:
       - "8888:8888"
     volumes:
       - ./workspace:/home/jovyan/work
+      - /mnt/object:/mnt/object:rw
     environment:
       - RAY_ADDRESS=http://ray-head:8265
+      - TRAINING_JSON_PATH=/mnt/object/training.json
+      - VALIDATION_JSON_PATH=/mnt/object/validation.json
+      - TESTING_JSON_PATH=/mnt/object/testing.json
+      - ARTIFACT_PATH=/mnt/object/artifacts
     depends_on:
       - ray-head
 
@@ -173,5 +187,5 @@ services:
 volumes:
   grafana_storage:
   ray_tmp:
-  minio_data:
   postgres_data:
+  workspace:
